### ISSUE TITLE
There is no `workbook_loader` as shown in example at README.md

### ISSUE THREAD

**Issue by igormukhingmailcom** [akeneo-labs/SpreadsheetParserBundle#2]
Hi.

Looks like there is not valid example at README.md:
```php
        $loader = $this->container->get('akeneo_spreadsheet_parser.workbook_loader');
```

But service `akeneo_spreadsheet_parser.workbook_loader` [not exists](https://github.com/akeneo/SpreadsheetParserBundle/search?utf8=%E2%9C%93&q=workbook_loader&type=Code).

**Comment by damien-carcel** [comment]
Your fix has been merged. Thank you for your participation (and sorry for the veeerry long reactivity on our side).
